# Generated by Django 5.2.8 on 2026-01-19 10:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company name or person's full name", max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Main contact person (for businesses)', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Primary email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Phone number with country code', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Full postal address')),
                ('tax_id', models.CharField(blank=True, help_text='For invoice generation', max_length=50, verbose_name='Tax ID/VAT Number')),
                ('is_business', models.BooleanField(default=False, help_text='Check if this is a business (not individual)', verbose_name='Business Customer')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=10000.0, help_text='Maximum amount customer can owe', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount currently owed by customer', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sales_custo_name_980413_idx'), models.Index(fields=['email'], name='sales_custo_email_b3bee2_idx'), models.Index(fields=['is_active'], name='sales_custo_is_acti_1b1d19_idx')],
            },
        ),
    ]
